Graph break in user code at /mnt/ssd1/shreyansh/home_dir/misc_experiments/torch_compile_usage/identify_breaks_restarts/buggy.py:6
Reason: Unsupported: builtin: print [<class 'torch._dynamo.variables.constant.ConstantVariable'>, <class 'torch._dynamo.variables.lists.SizeVariable'>] False
User code traceback:
  File "/mnt/ssd1/shreyansh/home_dir/misc_experiments/torch_compile_usage/identify_breaks_restarts/buggy.py", line 6, in f1
    print("f1 logging: x shape:", x.shape)  # <-- Graph break due to printing.

Traceback (most recent call last):
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 659, in wrapper
    return inner_fn(self, inst)
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1658, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 897, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 1004, in call_function
    return handler(tx, args, kwargs)
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/variables/builtin.py", line 838, in <lambda>
    return lambda *args: unimplemented(error_msg)
  File "/home/shreyansh/.local/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 317, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: builtin: print [<class 'torch._dynamo.variables.constant.ConstantVariable'>, <class 'torch._dynamo.variables.lists.SizeVariable'>] False
